parea-ai/parea-sdk-py

parea/schemas/models.py

available features

---

README.md
parea/api_client.py
pyproject.toml

correct url

---

.env.sample
parea/client.py
parea/schemas/models.py
pyproject.toml

PAI-198-allow-capturing-of-feedback-to-a-trace-via-sdk

---

parea/wrapper/__init__.py
parea/wrapper/openai.py
parea/wrapper/wrapper.py

fix: fix typo

---

parea/cookbook/tracing_with_Parea_sdk.ipynb
parea/cookbook/tracing_with_agent.py
parea/cookbook/tracing_with_deployed_prompt.py
parea/cookbook/tracing_with_open_ai_endpoint_directly.py
parea/cookbook/tracing_without_deployed_prompt.py
pyproject.toml

update text in cookbook

---

parea/client.py
parea/cookbook/tracing_with_agent.py
parea/cookbook/tracing_with_deployed_prompt.py
parea/cookbook/tracing_with_open_ai_endpoint_directly.py
parea/utils/trace_utils.py
parea/wrapper/wrapper.py
pyproject.toml

feat: measure latency in trace decorator

---

parea/helpers.py
pyproject.toml

use time.strftime for to_date_and_time_string

---

parea/utils/trace_utils.py
parea/wrapper/wrapper.py
pyproject.toml

fix: exception swallowed

---

parea/utils/trace_utils.py
parea/utils/universal_encoder.py
pyproject.toml

feat: add universial json serializer

---

parea/evals/chat.py
parea/evals/general.py
parea/evals/rag.py
parea/evals/summary.py
parea/evals/utils.py
parea/schemas/models.py
parea/wrapper/openai.py
parea/wrapper/wrapper.py
poetry.lock
pyproject.toml

Pai 402 add example evaluation functions

---

parea/evals/general.py
parea/evals/rag.py
parea/evals/utils.py
pyproject.toml

feat: add guardrails for llm vs llm

---

README.md
parea/cookbook/tracing_with_agent.py
parea/cookbook/tracing_without_deployed_prompt.py
parea/evals/chat.py
parea/evals/general.py
parea/evals/rag.py
parea/schemas/log.py
parea/schemas/models.py
parea/wrapper/openai.py

refactor: move log into its own class

---

parea/client.py
parea/cookbook/langchain/trace_langchain_rag_question_answering.py
parea/cookbook/tracing_with_openai_with_functions.py
parea/evals/rag/answer_context_faithfulness_binary.py
parea/schemas/models.py
parea/wrapper/openai.py
pyproject.toml

fix old openai function calling parser, handle parent trace id in logger

---

README.md
parea/__init__.py
parea/client.py
parea/cookbook/tracing_and_evaluating_openai_endpoint.py
parea/evals/chat/goal_success_ratio.py
parea/evals/general/answer_relevancy.py
parea/evals/general/llm_grader.py
parea/evals/general/lm_vs_lm.py
parea/evals/general/self_check.py
parea/evals/rag/answer_context_faithfulness_binary.py
parea/evals/rag/answer_context_faithfulness_precision.py
parea/evals/rag/answer_context_faithfulness_statement_level.py
parea/evals/rag/context_query_relevancy.py
parea/evals/rag/context_ranking_listwise.py
parea/evals/rag/context_ranking_pointwise.py
parea/evals/summary/factual_inconsistency_binary.py
parea/evals/summary/factual_inconsistency_scale.py
parea/evals/summary/likert_scale.py
parea/experiment/experiment.py
parea/schemas/log.py
pyproject.toml

Docs experiments improvement

---

parea/utils/trace_utils.py
pyproject.toml

fix: not JSON serializable inputs

---

parea/client.py
parea/cookbook/tracing_with_open_ai_endpoint_directly.py
parea/wrapper/openai.py
pyproject.toml

Pai 522 enable instantiated oai client automatic logging in python sdk

---

parea/client.py
parea/cookbook/langchain/trace_langchain_simple.py
pyproject.toml

add cookbook example, loadenv in client

---

parea/api_client.py
pyproject.toml

feat: update base url

---

parea/client.py
parea/experiment/experiment.py
pyproject.toml

Pai 533 create experiments overview table

---

parea/evals/utils.py
parea/utils/trace_integrations/langchain.py
parea/wrapper/utils.py
parea/wrapper/wrapper.py
pyproject.toml

fix: ignore traces from evaluation metrics

---

parea/client.py
pyproject.toml
requirements.txt

fix: typo error

---

parea/api_client.py
parea/experiment/experiment.py
parea/utils/trace_utils.py
pyproject.toml

feat: optimize experiments for async

---

parea/evals/general/answer_matches_target_recall.py
parea/evals/rag/answer_context_faithfulness_precision.py
parea/evals/utils.py
pyproject.toml

fix: provide default for non openai models

---

parea/api_client.py
parea/client.py
parea/experiment/experiment.py
parea/schemas/models.py
parea/utils/trace_utils.py
pyproject.toml

sdk code updates

---

parea/evals/utils.py
parea/schemas/models.py
pyproject.toml

add helpers

---

parea/wrapper/wrapper.py
poetry.lock
pyproject.toml

fix wrapper import

---

parea/wrapper/openai.py
pyproject.toml

fix: openai lgos not appearing

---

parea/wrapper/openai.py
parea/wrapper/wrapper.py
pyproject.toml

Pai 594 fix async openai wrapper

---

parea/api_client.py
parea/cache/cache.py
parea/cache/in_memory.py
parea/cache/redis.py
parea/cookbook/data/openai_input_examples.py
parea/cookbook/tracing_and_evaluating_openai_endpoint.py
parea/cookbook/tracing_open_ai_streams.py
parea/cookbook/tracing_with_openai_requests_api.py
parea/evals/general/llm_grader.py
parea/evals/rag/answer_context_faithfulness_statement_level.py
parea/evals/rag/context_query_relevancy.py
parea/evals/rag/context_ranking_listwise.py
parea/evals/rag/context_ranking_pointwise.py
parea/evals/rag/percent_target_supported_by_context.py
parea/utils/trace_utils.py
parea/wrapper/openai.py
parea/wrapper/openai_raw_api_tracer.py
parea/wrapper/utils.py
pyproject.toml

Streaming tracing for openai api direct

---

parea/client.py
parea/schemas/models.py
parea/utils/trace_utils.py
parea/wrapper/wrapper.py
pyproject.toml

Pai 596 enable filtering on nested outputs

---

parea/evals/general/lm_vs_lm.py
parea/evals/general/self_check.py
parea/evals/utils.py
parea/schemas/log.py
parea/wrapper/utils.py
pyproject.toml

Pai 420 add json mode open ai

---

parea/api_client.py
parea/client.py
parea/cookbook/langchain/trace_langchain_rag_question_answering.py
parea/cookbook/langchain/trace_langchain_simple.py
parea/parea_logger.py
parea/schemas/log.py
parea/schemas/models.py
pyproject.toml

WIP: Function format needs fixing

---

parea/cookbook/tracing_azure_open_ai.py
parea/wrapper/openai.py
pyproject.toml

fix: openai azure streaming

---

parea/cookbook/data/openai_input_examples.py
parea/schemas/log.py
parea/wrapper/utils.py
pyproject.toml

Pai 565 add new 0125 open ai models update pricing

---

pyproject.toml

fix(version): bump

---

parea/utils/trace_utils.py
pyproject.toml

feat: enable applying evaluation only on fraction of traces

---

parea/schemas/models.py
pyproject.toml

fix(deploy): functions response for deployed prompt to str

---

parea/utils/universal_encoder.py
pyproject.toml

Add pydantic encoder

---

pyproject.toml

feat(version): bump v.56

---

parea/experiment/dvc.py
pyproject.toml

Feat auto track created dvc files in git

---

parea/experiment/dvc.py
pyproject.toml

fix: check if file exists

---

parea/experiment/dvc.py
pyproject.toml

fix: checking if file has been committed

---

parea/api_client.py
parea/wrapper/openai.py
parea/wrapper/utils.py
pyproject.toml

feat(openai): add tracing for tool call streaming

---

parea/__init__.py
parea/cookbook/langchain/trace_langchain_RAG_evals.py
parea/cookbook/langchain/trace_langchain_anthropic_function_calling.py
parea/cookbook/langchain/trace_langchain_bedrock_rag.py
parea/cookbook/langchain/trace_langchain_rag_agents.py
parea/cookbook/langchain/trace_langchain_rag_question_answering.py
parea/cookbook/langchain/trace_langchain_simple.py
pyproject.toml

fix(imports): import langchain tracer seperatly

---

parea/experiment/experiment.py
parea/utils/trace_utils.py
pyproject.toml

fix: inject target during experiments

---

parea/evals/general/__init__.py
parea/evals/general/semantic_similarity.py

feat: add semantic similarity

---

parea/api_client.py
parea/utils/trace_utils.py
pyproject.toml

add comments to trace insert

---

parea/cookbook/tracing_azure_open_ai.py
parea/utils/trace_utils.py
pyproject.toml

ignore non serializable

---

parea/utils/trace_utils.py
parea/utils/universal_encoder.py
pyproject.toml

move json exception handling into encoder

---

parea/utils/trace_utils.py
parea/utils/universal_encoder.py
pyproject.toml

swallow exception on serialization for trace

---

parea/cookbook/tracing_without_deployed_prompt.py
parea/evals/utils.py
parea/wrapper/utils.py
pyproject.toml

fix(encode): if error return 0

---

parea/cookbook/run_experiment_using_saved_test_collection.py
parea/cookbook/tracing_without_deployed_prompt.py
parea/experiment/experiment.py
parea/utils/trace_utils.py
parea/wrapper/wrapper.py

Users code should not be impacted by errors originating in Parea client
document.

fix(errors): swallow trace errors

---

parea/client.py
parea/experiment/datasets.py
parea/schemas/models.py

feat(add-test-cases): add test cases to existing dataset

---

parea/cookbook/run_experiment.py
parea/cookbook/run_experiment_using_saved_test_collection.py
parea/cookbook/tracing_without_deployed_prompt.py
parea/experiment/experiment.py
parea/utils/trace_utils.py
parea/wrapper/wrapper.py
pyproject.toml

Reverts parea-ai/parea-sdk-py#446

Revert "fix(errors): swallow trace errors"

---

parea/client.py
parea/cookbook/enpoints_for_datasets.py
parea/cookbook/run_experiment.py
parea/experiment/experiment.py
parea/helpers.py
poetry.lock
pyproject.toml

feat(ntrails): run experiment on same data n times

---

README.md
parea/schemas/models.py
pyproject.toml

feat: only require that eval score is convertible to float

---

parea/parea_logger.py
parea/utils/trace_utils.py
pyproject.toml

fix: make using target safe

---

parea/utils/universal_encoder.py
pyproject.toml

fix: prettify json dumps

---

parea/utils/trace_utils.py
pyproject.toml

feat: enable skipping eval functions

---

parea/experiment/experiment.py
pyproject.toml

bump to 4 seconds sleep

---

parea/client.py
parea/experiment/experiment.py
parea/schemas/models.py
pyproject.toml

feat: add metadata to experiments

---

parea/client.py
parea/cookbook/enpoints_for_datasets.py
parea/cookbook/run_experiment_using_saved_test_collection.py
parea/experiment/experiment.py
parea/schemas/models.py
pyproject.toml

Pai 672 get or use datasets by id or name in sdks

---

parea/api_client.py
parea/client.py
parea/cookbook/tracing_with_agent.py
parea/helpers.py
parea/parea_logger.py
parea/schemas/models.py
parea/utils/trace_utils.py
pyproject.toml

serialize metadata before sending to across wire

---

parea/utils/trace_integrations/langchain.py
pyproject.toml

fix import

---

parea/__init__.py
parea/cookbook/langchain/trace_langchain_simple.py
parea/cookbook/tracing_with_agent.py
parea/helpers.py
parea/utils/trace_integrations/langchain.py
parea/utils/trace_utils.py
parea/wrapper/wrapper.py
pyproject.toml

Pai 721 timestamps are wrong for other timezones

---

parea/client.py
parea/wrapper/wrapper.py
pyproject.toml

Pai 724 auto wrap openai client classes

---

pyproject.toml

drop httpx version requirement

---

poetry.lock

poetry lock

---

parea/api_client.py
parea/client.py
parea/cookbook/run_experiment_balanced_acc.py
parea/evals/dataset_level/__init__.py
parea/evals/dataset_level/balanced_acc.py
parea/evals/utils.py
parea/experiment/experiment.py
parea/schemas/log.py
parea/schemas/models.py
parea/utils/trace_utils.py
pyproject.toml

Pai 737 enable dataset level evaluation metrics

---

parea/client.py
parea/cookbook/run_experiment_balanced_acc.py
parea/experiment/experiment.py
parea/utils/trace_utils.py

Pai 754 fix parallelization in experiments

---

parea/schemas/log.py
pyproject.toml

fix: add safe prompt

---

parea/wrapper/__init__.py
parea/wrapper/openai/OpenAIAsyncStreamWrapper.py
parea/wrapper/openai/OpenAIStreamWrapper.py
parea/wrapper/openai/openai.py
parea/wrapper/openai_raw_api_tracer.py
parea/wrapper/wrapper.py

Pai 756 fix async streaming with instructor

---

pyproject.toml

fix: relax tiktoken

---

parea/schemas/log.py
parea/wrapper/utils.py

feat: add tool role

---

parea/client.py
parea/cookbook/tracing_with_images_open_ai.py
parea/helpers.py
parea/schemas/models.py
parea/utils/trace_utils.py
pyproject.toml

handle images

---

parea/cookbook/langchain/trace_langchain_simple.py
parea/helpers.py
parea/utils/trace_integrations/langchain.py
pyproject.toml

fix langchain callback

---

parea/cookbook/tracing_tool_calling.py
parea/helpers.py
pyproject.toml

fix: openai tool calling in message

---

parea/helpers.py
pyproject.toml

fix: using completion endpoint

---

parea/experiment/experiment.py
parea/schemas/models.py
pyproject.toml

feat: add individual experiment scores

---

parea/wrapper/utils.py
pyproject.toml

fix: model not implemented

---

parea/client.py
parea/constants.py
parea/schemas/models.py
parea/wrapper/openai_beta_wrapper.py
parea/wrapper/utils.py

assistant MVP no streaming

---

pyproject.toml

version up assistant tracing

---

parea/client.py
pyproject.toml

missing import

---

parea/client.py
parea/constants.py
parea/cookbook/tracing_with_parea_streaming.py
pyproject.toml

remove flag for assistants

---

parea/evals/utils.py
pyproject.toml

fix: safe encoding

---

parea/schemas/log.py
parea/types.py
parea/wrapper/openai/openai.py
pyproject.toml

Pai 870 measure ttft

---

parea/cookbook/fetching_and_using_parea_deployments.py
parea/cookbook/langchain/trace_langchain_with_deployed_prompt.py

add cookbooks

---

parea/wrapper/utils.py
pyproject.toml

feat: enable tool role in playground

---

parea/utils/trace_utils.py
pyproject.toml

return none if no result

---

parea/client.py
parea/constants.py
parea/cookbook/tracing_anthropic.py
parea/wrapper/anthropic/anthropic.py
parea/wrapper/anthropic/stream_wrapper.py
parea/wrapper/utils.py
pyproject.toml

Pai 886 add claude auto tracing

---

parea/client.py
pyproject.toml

chore: bump version

---

parea/schemas/log.py
pyproject.toml

fix: fix llm inputs

---

parea/cookbook/tracing_openai_assistant_endpoint.py

add assistants cookbook

---

parea/wrapper/openai/openai.py
parea/wrapper/utils.py

fix: no strip

---

parea/experiment/dvc.py
pyproject.toml

Pai 839 fix experiments without git initialization

---

parea/cookbook/langchain/trace_langchain_RAG_evals.py
parea/cookbook/langchain/trace_langchain_rag_question_answering.py
poetry.lock
pyproject.toml

remove chroma

---

parea/client.py
parea/cookbook/guidance/tracing_guidance.py
parea/evals/general/answer_matches_target_llm_grader.py
parea/evals/general/answer_matches_target_recall.py
parea/evals/general/levenshtein.py
parea/evals/general/self_check.py
parea/evals/general/semantic_similarity.py
parea/evals/rag/context_query_relevancy.py
parea/evals/rag/context_ranking_listwise.py
parea/evals/rag/context_ranking_pointwise.py
parea/utils/trace_utils.py
poetry.lock
pyproject.toml

Pai 916 write s glang integration

---

parea/cookbook/langchain/trace_langchain_RAG_with_experiment.py
parea/cookbook/tracing_with_deployed_prompt.py
parea/evals/general/answer_matches_target_llm_grader.py
parea/evals/general/answer_matches_target_recall.py
parea/evals/general/levenshtein.py
parea/evals/general/semantic_similarity.py
parea/evals/rag/context_query_relevancy.py
parea/evals/rag/context_ranking_listwise.py
parea/evals/rag/context_ranking_pointwise.py
parea/evals/rag/percent_target_supported_by_context.py
parea/utils/trace_utils.py
pyproject.toml

Feat more eval updates

---

parea/cookbook/run_experiment_evas_with_reason.py
parea/evals/utils.py
parea/experiment/experiment.py
parea/schemas/log.py
parea/utils/trace_utils.py
pyproject.toml

feat: enable reason field in eval metrics

---

parea/client.py
parea/cookbook/run_experiment.py
parea/cookbook/run_experiment_balanced_acc.py
parea/cookbook/run_experiment_evas_with_reason.py
parea/experiment/cli.py
parea/experiment/experiment.py
parea/schemas/models.py
pyproject.toml

feat: introduce experiment name

---

parea/cookbook/langchain/trace_langchain_RAG_with_experiment.py

add experiment name

---

parea/cookbook/data/anthropic_tool_use_examples.py
parea/cookbook/tracing_anthropic_tool_use.py
parea/wrapper/anthropic/anthropic.py

Pai 966 anthropic beta tool use support

---

parea/wrapper/wrapper.py
pyproject.toml

fix: don't log parent in wrapper

---

parea/cookbook/langchain/trace_langchain_azure_RAG_with_experiment.py
parea/evals/chat/goal_success_ratio.py
parea/evals/general/answer_matches_target_llm_grader.py
parea/evals/general/answer_relevancy.py
parea/evals/general/llm_grader.py
parea/evals/general/lm_vs_lm.py
parea/evals/general/semantic_similarity.py
parea/evals/rag/answer_context_faithfulness_binary.py
parea/evals/rag/answer_context_faithfulness_statement_level.py
parea/evals/rag/context_has_answer.py
parea/evals/rag/context_query_relevancy.py
parea/evals/rag/context_ranking_listwise.py
parea/evals/rag/context_ranking_pointwise.py
parea/evals/rag/percent_target_supported_by_context.py
parea/evals/summary/factual_inconsistency_binary.py
parea/evals/summary/factual_inconsistency_scale.py
parea/evals/summary/likert_scale.py
parea/evals/utils.py
pyproject.toml

support azure in evals

---

parea/experiment/experiment.py

fix experiment run url

---

parea/utils/universal_encoder.py
pyproject.toml

fix: fix stream wrapper import for old openai

---

parea/client.py
pyproject.toml

fix: no api call if no api key is set

---

parea/client.py
parea/helpers.py
pyproject.toml

feat: expose trace log via api

---

parea/evals/utils.py
pyproject.toml

fix: get tokens if no model is provided

---

parea/cookbook/simple_experiment_with_openai.py

add cookbook example openai experiment

---

parea/wrapper/wrapper.py
pyproject.toml

feat: capture inputs to auto-traced LLM calls

---

parea/cookbook/tracing_templated_llm_calls.py
parea/wrapper/utils.py
parea/wrapper/wrapper.py
pyproject.toml

fix: capture inputs to auto-traced LLM calls with json fields

---

parea/client.py
parea/cookbook/list_experiments.py
parea/schemas/models.py

feat: list experiment uuids

---

parea/client.py
parea/cookbook/list_experiments.py
parea/helpers.py
parea/schemas/models.py
pyproject.toml

feat: fetch logs for experiment

---

parea/client.py
parea/cookbook/list_experiments.py
parea/schemas/models.py
pyproject.toml

feat: extend experiments list endpoint

---

parea/evals/rag/context_query_relevancy.py
parea/evals/rag/context_ranking_listwise.py
parea/evals/rag/context_ranking_pointwise.py
parea/evals/rag/percent_target_supported_by_context.py
parea/evals/utils.py
pyproject.toml

chore: update evals list parsing

---

parea/schemas/models.py

Change annotation from dict -> Dict to support Python < 3.9

---

.github/workflows/build.yml
parea/schemas/models.py
pyproject.toml
tests/test_import.py

fix: support python 3.8

---

parea/__init__.py
parea/api_client.py
parea/client.py
parea/parea_logger.py
pyproject.toml

feat: integrate with sglang

---

parea/api_client.py
parea/cookbook/tracing_with_images_anthropic.py

Pai 897 claude auto tracing images

---

parea/client.py
parea/cookbook/simple_experiment_with_openai.py
parea/cookbook/tracing_and_evaluating_openai_endpoint.py
parea/cookbook/tracing_without_deployed_prompt.py
parea/evals/utils.py
parea/experiment/experiment.py
parea/schemas/models.py
parea/utils/trace_utils.py
parea/wrapper/openai_raw_api_tracer.py
parea/wrapper/utils.py
pyproject.toml

Send trace logs when complete

---

parea/cookbook/dspy/tracing_and_evaluation_tutorial.ipynb
parea/experiment/experiment.py
parea/utils/trace_integrations/dspy.py
pyproject.toml

feat: add dspy cookbook

---

parea/experiment/experiment.py
pyproject.toml

fix: quote experiment name

---

parea/cookbook/use_dataset_for_finetuning.py
parea/schemas/models.py
pyproject.toml

feat: add write to finetune jsonl

---

parea/client.py
parea/schemas/models.py
pyproject.toml

add uuids to filter conditions

---

parea/cookbook/langchain/trace_langchain_inside_trace_decorator.py
parea/schemas/models.py
parea/utils/trace_integrations/langchain.py
parea/utils/trace_utils.py
pyproject.toml

feat: trace langchain calls within decorator

---

parea/cookbook/tracing_anthropic_tool_use.py
parea/wrapper/anthropic/anthropic.py
pyproject.toml

fix: deepcopy anthropic functions

---

parea/api_client.py
pyproject.toml

Fix retry on read error

---

parea/api_client.py
pyproject.toml

fix: retry on RemoteProtocolError

---

parea/experiment/experiment.py
parea/helpers.py
parea/utils/trace_integrations/langchain.py
parea/utils/trace_utils.py
parea/wrapper/openai_beta_wrapper.py
parea/wrapper/wrapper.py
pyproject.toml

feat: enable disabling logging

---

parea/cookbook/async_experiments.py
parea/experiment/experiment.py

add async completion to cookbook

---

parea/client.py
parea/cookbook/instructor_evals.py
parea/cookbook/tracing_templated_llm_calls.py
parea/utils/trace_integrations/dspy.py
parea/utils/trace_integrations/instructor.py
parea/utils/trace_integrations/wrapt_utils.py
parea/utils/trace_utils.py
pyproject.toml

Pai 1103 instructor validation error callback

---

parea/constants.py
pyproject.toml

add gpt-4o pricing

---

parea/client.py
pyproject.toml

Fix ignore no project created

---

parea/utils/trace_utils.py
pyproject.toml

fix(trace): function returning 0 got converted to None in trace log

---

parea/client.py
parea/cookbook/trace_marvin.py
pyproject.toml

feat: auto trace marvin

---

parea/cookbook/tracing_tool_calling.py
parea/cookbook/tracing_with_images_open_ai.py
parea/cookbook/tracing_with_open_ai_endpoint_directly.py
parea/parea_logger.py
parea/schemas/models.py
parea/utils/trace_utils.py
parea/wrapper/anthropic/anthropic.py
parea/wrapper/openai/openai.py
parea/wrapper/utils.py
parea/wrapper/wrapper.py
pyproject.toml

Add depth and execution order

---

parea/experiment/experiment.py
pyproject.toml

Fix datset level eval fail exp

---

parea/experiment/experiment.py
pyproject.toml

fix: failing dataset level eval failing exp results

---

parea/cookbook/langchain/trace_class_call_method.py

fix(cookbook): pass varible into prompt template

---

parea/client.py
parea/cookbook/parea_llm_proxy/dynamic_few_shot_injection.py
parea/cookbook/use_dataset_for_finetuning.py
parea/schemas/log.py
pyproject.toml

Datasets updates

---

parea/__init__.py
parea/utils/trace_integrations/langchain.py
parea/utils/trace_utils.py
pyproject.toml

helper for Lambdas

---

parea/utils/trace_integrations/langchain.py
pyproject.toml

handle older langchain version

---

parea/client.py
parea/cookbook/openai/dynamic_few_shot_injection_with_evals.py
parea/helpers.py
parea/schemas/models.py
pyproject.toml

Pai 1225 get scores from trace id endpoint sdkp

---

parea/experiment/experiment.py
pyproject.toml

refactor: create experiment uuid outside run method

---

parea/client.py
pyproject.toml

fix: optional param in openai auto trace

---

parea/experiment/experiment.py
pyproject.toml

fix: experiment run name creation

---

parea/client.py
parea/cookbook/guidance/tracing_guidance.py
parea/cookbook/langchain/trace_langchain_RAG_evals.py
parea/cookbook/parea_llm_proxy/tracing_with_parea_streaming.py
parea/evals/utils.py
parea/experiment/cli.py
parea/parea_logger.py
parea/schemas/models.py
parea/utils/trace_integrations/instructor.py
parea/wrapper/utils.py
pyproject.toml

add root_trace_id to update

---

parea/cookbook/evals_and_experiments/modify_dataset_before_experiment.py
parea/evals/utils.py
pyproject.toml

new cookbook, set openai.api_type

---

parea/schemas/log.py
pyproject.toml

fix: model params types

---

parea/cookbook/langchain/trace_langchain_simple.py
parea/utils/universal_encoder.py
pyproject.toml

safe serialize obj

---

parea/cookbook/evals_and_experiments/list_experiments.py
parea/schemas/log.py
parea/schemas/models.py
pyproject.toml

Fix experiment deserialization

---

parea/cookbook/evals_and_experiments/run_experiment_using_saved_test_collection.py
parea/experiment/experiment.py
parea/schemas/models.py
parea/utils/trace_integrations/instructor.py
pyproject.toml

Pai 1264 finished experiment even on trace fail flag to fail on first

---

parea/client.py
parea/helpers.py
poetry.lock
pyproject.toml

Avoid nested cattrs check on TraceLogTree

---

parea/cookbook/evals_and_experiments/RAG_experiment_with_auto_evals.py
parea/cookbook/parea_llm_proxy/tracing_with_agent.py
poetry.lock
pyproject.toml

add q&a auto eval cookbook

---

parea/schemas/models.py
pyproject.toml

Add deployment ver num

---

parea/schemas/models.py
pyproject.toml

fix to float

---

parea/cookbook/instructor/instructor_streaming.py
parea/schemas/models.py
parea/utils/trace_integrations/instructor.py
parea/wrapper/wrapper.py
pyproject.toml

Pai 1313 instructor integration key error

---

parea/constants.py
parea/cookbook/instructor/instructor_streaming.py
pyproject.toml

feat: add sonnet 3.5

---

parea/wrapper/anthropic/anthropic.py
pyproject.toml

fix: track system prompt for anthropic

---

parea/utils/trace_utils.py
parea/wrapper/wrapper.py
pyproject.toml

feat: trace evals

---

cookbook/openai/simple_experiment_with_openai.py
parea/utils/trace_utils.py
pyproject.toml

fix: target being zero

---

parea/client.py
parea/parea_logger.py
pyproject.toml

refetch project uuid if missing

---

cookbook/evals_and_experiments/route_llm_experiment.py

route llm cookbook

---

cookbook/parea_llm_proxy/deployments/fetching_and_using_parea_deployments.py
cookbook/parea_llm_proxy/deployments/tracing_with_deployed_prompt.py
cookbook/parea_llm_proxy/tracing_without_deployed_prompt.py
parea/schemas/log.py
pyproject.toml

feat(history): add history to completion

---

parea/schemas/models.py
parea/wrapper/openai/openai.py
pyproject.toml
tests/test_test_case_collection.py

Pai 1443 advanced test case filtering

---

parea/parea_logger.py
parea/utils/trace_integrations/langchain.py
parea/utils/trace_integrations/langchain_utils.py
pyproject.toml

Improve lc errors

---

parea/wrapper/openai/openai.py
pyproject.toml

type checking on old openai versions

---

parea/experiment/dvc.py
pyproject.toml

fix: git not available

---

cookbook/openai/tracing_templated_llm_calls.py
parea/wrapper/wrapper.py
pyproject.toml

feat: capture metadata for llm calls

---

cookbook/fetch_logs.py
parea/client.py
parea/helpers.py
parea/schemas/models.py
pyproject.toml

feat: fetch logs via api

---

cookbook/openai/tracing_with_openai_with_functions.py
parea/schemas/models.py
parea/utils/trace_integrations/langchain.py
parea/utils/trace_utils.py
pyproject.toml

feat: add log sampling

---

parea/client.py
parea/parea_logger.py
pyproject.toml

Pai 1462 ensure that failed parea project creation doesnt cause any issues

---

cookbook/instructor/instructor_streaming.py
cookbook/openai/tracing_open_ai_streams.py
parea/utils/trace_integrations/instructor.py
parea/utils/trace_utils.py
parea/wrapper/anthropic/anthropic.py
parea/wrapper/anthropic/stream_wrapper.py
pyproject.toml

Pai 1464 make trace decorator work with iterator responses

---

cookbook/anthropic/tracing_anthropic_tool_use.py
parea/wrapper/anthropic/anthropic.py
pyproject.toml

fix: import anthropic json delta type

---

parea/constants.py

add pricing

---

parea/helpers.py
parea/schemas/log.py
pyproject.toml

fix: correct creation of trace log from api response

---

parea/experiment/experiment.py
pyproject.toml

refactor: add traceback to experiment failure

---

parea/helpers.py
pyproject.toml

fix: filter for valid fields

---

cookbook/evals_and_experiments/experiment_test_substeps.py
parea/experiment/experiment.py
pyproject.toml

add prefix to run_names in experiment

---

parea/schemas/log.py
pyproject.toml

fix: convert output to tool use response

---

cookbook/evals_and_experiments/parea_evaluation_deepdive.ipynb
cookbook/parea_llm_proxy/deployments/tracing_with_deployed_prompt.py
parea/api_client.py
pyproject.toml

add broader retry on http client

---

poetry.lock
pyproject.toml

add orjson

---

poetry.lock
pyproject.toml

jupyter dev dependency

---

parea/schemas/models.py
pyproject.toml

feat: store comment from user feedback

---

cookbook/openai/tracing_with_openai_with_functions.py
parea/constants.py
pyproject.toml

feat(models): add new openai models

---

parea/client.py
pyproject.toml

don't raise on parea error

---

parea/wrapper/utils.py
pyproject.toml

add new openai models to tokenizer
